### ISSUE TITLE
Move banner ad at bottom of post above Reference box

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEM#100]
If it's an easy fix, move banner ad above rather than below the references box for each post. Hopefully higher "active view" rate.

**Comment by dsifford** [comment]
Are you sure you want to do that?

IMHO, it'll cheapen the look of the site. It'll also be much more difficult to do.

**Comment by michellealiem** [comment]
I figure no one really looks at the references per se since your superscript in line numbers take you to the right link right away. Some posts have super long references and definitely no one would see the ad. 

If it's easy to do, would change. When I manually inserted the script, that's where the ad landed and so I thought the look wasn't a dealbreaker. 

Sounds like it's a pain to change, so let's leave as-is. Thanks for checking.

**Comment by dsifford** [comment]
Yeah, it's difficult to do because in order to do it programmatically to all posts, you have to put it after all of the post content. There's no way to know where the references are in the content of a post (or if the post even has references) on the large scale.
