### ISSUE TITLE
Error with uploading new media files

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEM#113]
Immediately after uploading a new media file, I get this error (at bottom of image). The image seems to get uploaded fine into the library. Not sure why the error. 

<img width="881" alt="screenshot 2018-02-01 13 41 20" src="https://user-images.githubusercontent.com/15097022/35704935-db5c18d2-0755-11e8-90a9-7625e3e84e27.png">

**Comment by dsifford** [comment]
Done
