### ISSUE TITLE
Menu-based category results: Add more pagination options

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEM#120]
When clicking on a category from the menu (e.g. Healthy in EM, or Tricks of the Trade), it only allows you to page forward or back by one page. In contrast, if you use Algolia search for "healthy in EM", it gives you the ability to skip up to 7 pages ahead and even to the end with one click. Can we do something like the Algolia version? Not a huge deal, but as we have a lot of hits on a search, it is a pain to scroll through each page one by one.

Or is there a better way to give the viewer a better global view of all the posts before clicking on a specific one?

Screenshot 1 (click on Healthy in EM within menu)
Screenshot 2 (type Healthy in EM via search bar)

<img width="875" alt="screenshot 2018-12-20 14 49 56" src="https://user-images.githubusercontent.com/15097022/50315322-2aef9e00-0467-11e9-9c66-35075af49582.png"> 
<img width="782" alt="screenshot 2018-12-20 14 53 23" src="https://user-images.githubusercontent.com/15097022/50315326-2f1bbb80-0467-11e9-88b9-681d58c88c3a.png">

**Comment by dsifford** [comment]
![image](https://user-images.githubusercontent.com/5240018/51796999-76b20780-21ca-11e9-9c69-42f04193b522.png)

Done
