### ISSUE TITLE
Add Instagram to social media banner header

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEM#123]
Our Insta account is: https://www.instagram.com/aliemteam/
I tried to add under Social Media icons without success. https://www.aliem.com/wp-admin/themes.php?page=avada_options

**Comment by dsifford** [comment]
> I tried to add under Social Media icons without success.

That's my worry about sticking with Avada.. I've mangled the theme and options to such a high extent now that most of these options will not work. And adding them back will end up breaking our user interface.

Just something to think about.

**Comment by michellealiem** [comment]
Hmm, that's too bad. Advice on how to proceed? In the meantime can we swap out the Google Plus for Instagram since we don't use it anymore? It's a hacky temporizer, I realize.

**Comment by dsifford** [comment]
Yeah, just to clarify. Doing what's being requested in this issue thread is super easy and I'll get to it when I'm able to transition the site to the new infrastructure. Hoping this weekend.

**Comment by michellealiem** [comment]
Ah ok. I thought it was a problem with the Insta icon specifically. It's a more global issue. Yea, definitely something we're going to have to consider once things settle down a bit. Thanks for clarifying.

**Comment by dsifford** [comment]
Re: how to proceed: The best option would be to clean the slate, get off Avada completely, and just apply our style to an optimized, best-practice starter theme like [underscores](https://github.com/Automattic/_s)

**Comment by michellealiem** [comment]
Nice. Then it definitely make sense not to use features like Fusion, that's tethered to Avada and other themes. Sticking with Gutenberg sounds like a reasonable forecasted plan to me.

**Comment by dsifford** [comment]
\*\*long, satisfying sigh of relief\*\*

**Comment by dsifford** [comment]
Done
