### ISSUE TITLE
Right column typeface 

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEM#32]
Can we make all the font sizes/line heights look like the ALiEM sock description one? The Top Posts box’s line height looks too tall for the font size. Book Club box’s font size looks slightly too big, given the titles are so small font.

![right column](https://cloud.githubusercontent.com/assets/15097022/19833550/b704e00c-9df9-11e6-8a46-26ed9204a113.png)

**Comment by dsifford** [comment]
@michellealiem  Font size is pretty strict for the popular posts widget. There's just too much text to be able to go any larger. 

Thoughts on what to do there?

**Comment by dsifford** [comment]
Just fixed it. Gonna post the fix with the others when I'm all done. I'm pretty sure you'll approve, but let me know if not.

**Comment by michellealiem** [comment]
@dsifford I DO like it! Can we change the typeface similarly for the first 2 boxes as well? 
![screen shot 2016-10-30 at 7 59 00 pm](https://cloud.githubusercontent.com/assets/15097022/19842970/53c26d2e-9edb-11e6-91a5-e3040b49af2f.png)
