### ISSUE TITLE
Get CME SVG: URL shortcode doesn't work

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEM#37]
https://www.aliem.com/2016/5-tips-managing-pain-older-adults/

[svg series="cme-button" align="center" width="200px" url="https://foambase.org/story.php?title=5-tips-for-managing-pain-in-older-adults-aliem-#questionstop"]

**Comment by dsifford** [comment]
@michellealiem 

This was changed. You should have gotten the email I sent to Ben et al.

It's now `[cme-button url="<enter-url-here>"]`
