### ISSUE TITLE
3 links don't work in right column widget for Incubators

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEM#42]
All 3 links go to https://www.aliem.com/# even though the Widget HTML looks ok.

![screen shot 2016-11-09 at 6 45 29 pm](https://cloud.githubusercontent.com/assets/15097022/20162868/d79591f2-a6ac-11e6-970c-e15ae629d7fe.png)

**Comment by dsifford** [comment]
Fixed
