### ISSUE TITLE
Header line height 

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEM#6]
Need to increase line height for h3 at least on mobile

**Comment by dsifford** [comment]
Image:

![image](https://cloud.githubusercontent.com/assets/5240018/19750252/bd793142-9bbd-11e6-94ed-ef7065eea58a.png)

Also, I think that specific header element is h2 or h1

**Comment by michellealiem** [comment]
Oh right! Forgot that capsules posts like h1 and h2.
