### ISSUE TITLE
Fix Chrome table CSS

### ISSUE THREAD

**Issue by ghost** [aliemteam/ALiEM#84]
On Chrome browser, text is being inappropriately clipped into new line. Problem is: `display: table`

Noticed on page: https://www.aliem.com/wellness-think-tank/

![screen shot 2016-12-26 at 5 04 45 pm](https://cloud.githubusercontent.com/assets/7309097/21487977/a67897da-cb8d-11e6-9ac8-dfee7f7a6c85.png)

**Comment by dsifford** [comment]
@michellealiem @michelleclin <-- which one are you?

Also, I can't reproduce this now after fixing the other thing so keep an eye out for this

**Comment by michellealiem** [comment]
I believe I am michelleclin. Ok will keep lookout.

**Comment by michellealiem** [comment]
Scratch that. It's michellealiem. Deleted the other account!
